"""baseline: existing matches schema

Revision ID: 63cd79dc935b
Revises:
Create Date: 2026-08-09 06:25:59.948948

The `matches` table already existed before Alembic was adopted - it was
created by `Base.metadata.create_all()` in db.py and seeded with 32 rows by
seed.py. On the live database this revision is applied via `alembic stamp`,
which records the revision id in alembic_version WITHOUT running anything,
so the live table is never touched.

The create_table body below (autogenerated against an empty scratch database
while the model still had no `round` column) exists only so a FRESH database
can be built from migrations alone - with a `pass` body here, upgrading a
fresh database would crash on the next revision trying to ALTER a table that
was never created.

Guarded with has_table(): this revision is meant to be applied to an
existing database via `alembic stamp`, never `upgrade`. If someone runs
`upgrade` against a database that already has `matches` by mistake, the
guard makes that a clean no-op instead of a generic "relation already
exists" error from Postgres.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cd79dc935b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if sa.inspect(op.get_bind()).has_table('matches'):
        return
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_penalties', sa.Integer(), nullable=True),
    sa.Column('away_penalties', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('matches')
